import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {Modal} from "@/components/UI/Modal/Modal";
import {ModalHeaderProps} from "@/components/UI/Modal/ModalHeader/ModalHeaderProps";
import {ModalFooterProps} from "@/components/UI/Modal/ModalFooter/ModalFooterProps";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

    const header: ModalHeaderProps = {
        title: 'MyTitle',
        icon: '',
        buttonGroup: {
            buttons: [
                {
                    title: 'Btn1'
                },
                {
                    title: 'Btn2'
                },
                {
                    title: 'Btn3'
                },
            ]
        }
    }

    const footer: ModalFooterProps = {
        description: 'abc',
        buttonGroup: {
            buttons: [
                {
                    title: 'Btn1'
                },
                {
                    title: 'Btn2'
                },
            ]
        }
    }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Modal header={header} footer={footer}>Content</Modal>
      </main>
    </>
  )
}
